Add Python 3 support
Fix for:
Traceback (most recent call last):
  File "/Users/alex/Python-scripts/MH/python-parser/p3venv/lib/python3.5/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "/Users/alex/Python-scripts/MH/python-parser/p3venv/lib/python3.5/site-packages/scrapy/core/downloader/middleware.py", line 37, in process_request
    response = yield method(request=request, spider=spider)
  File "/Users/alex/Python-scripts/MH/python-parser/p3venv/lib/python3.5/site-packages/scrapy_proxies/randomproxy.py", line 65, in process_request
    proxy_address = random.choice(self.proxies.keys())
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/random.py", line 256, in choice
    return seq[i]
TypeError: 'dict_keys' object does not support indexing